build:
    tests:
        before:
            - pip install pylint-flask
checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: pylintrc
filter:
    excluded_paths:
        - 'tests/*'
