build:
    tests:
        before:
            - 'pip3 install pylint Coverage'
            - 'npm -g install jasmine'
        override:
            -
                command: 'coverage run --include="*veripeditus*" setup.py test'
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
            -
                command: 'pylint veripeditus --output-format=parseable --reports=n --include-naming-hint=y | tee pylint-data'
                analysis:
                    file: 'pylint-data'
                    format: 'pylint-parseable'
            -
                command: 'cd www; jasmine'
checks:
    python:
        code_rating: true
        duplicate_code: true
    javascript: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'www/dev/*'
        - 'www/spec/*'
