build:
    tests:
        before:
            - pip3 install pylint pylint-flask
        override:
            -
              command: 'coverage run --include="*veripeditus*" setup.py test; pylint veripeditus --output-format=parseable --reports=n --include-naming-hint=y | tee pylint-data'
              analysis:
                  file: 'pylint-data'
                  format: 'pylint-parseable'
              coverage:
                  file: '.coverage'
                  format: 'py-cc'
checks:
    python:
        code_rating: true
        duplicate_code: true
