build:
    tests:
        before:
            - pip3 install pylint pylint-flask
        override:
            -
              command: 'pylint veripeditus --output-format=parseable --reports=n --include-naming-hint=y | tee pylint-data'
              analysis:
                  file: 'pylint-data'
                  format: 'pylint-parseable'
